name: CD/CI Workflow

on: [push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Use Node 12.13 LTS
        uses: actions/setup-node@v1
        with:
          node-version: 12.13
      - name: Install NPM dependencies
        run: npm ci
      # - name: Audit with NPM
      #   run: npm audit
      - name: Lint with ESLint
        run: npm run lint
      - name: Build
        run: npm run build
        env:
          VUE_APP_FIREBASE_KEY: ${{ secrets.VUE_APP_FIREBASE_KEY }}
      - name: Archive production artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

  deploy:
    if: github.ref == 'refs/heads/master'
    name: Deploy
    needs: check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Deploy to Firebase Hosting
        uses: pizzafox/firebase-action@1.0.7
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        with:
          args: deploy
